name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
 RUN_ENV: ${{ vars.ACTION_ENV }}

jobs:
  setup:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log env
        run: |
          echo "code is running on: ${RUN_ENV}"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.3"

      - name: Tidy
        run: make tidy
        
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    needs: setup

    steps: 
      - uses: actions/checkout@v4

      - name: Build file
        run: make build
        
      - name: Zip file
        run: zip build/main.zip build/main

      - name: Deploy lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region:  ${{ secrets.AWS_REGION }}
          handler: main
          zip_file: build/main.zip
          function_name: free-order-be
  
