name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log env
      env: 
         TEST: ${{ vars.ACTION_ENV }}
      run:  |
        echo "code is running on: $TEST"

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Dotenv Action
      uses: falti/dotenv-action@v1.1.2      
      with:
        path: .env

    - name: Install
      run: make install

    # - name: Run test
    #   run: make test

    - name: Build
      run: make build
