name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
      
    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make install

    # - name: Run test
    #   run: make test

    - name: Run build
      run: make build
